name: project-econ434
channels:
  - main
  - conda-forge
  - defaults
dependencies:
  - _anaconda_depends=2024.02
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - abseil-cpp=20211102.0
  - aiobotocore=2.13.0
  - aiohttp=3.9.5
  - aioitertools=0.11.0
  - aiosignal=1.3.1
  - alabaster=0.7.16
  - altair=5.3.0
  - anaconda-catalogs=0.2.0
  - anaconda-client=1.12.3
  - anaconda-project=0.11.1
  - annotated-types=0.7.0
  - anyio=4.3.0
  - aom=3.5.0
  - appdirs=1.4.4
  - archspec=0.2.3
  - argon2-cffi=23.1.0
  - argon2-cffi-bindings=21.2.0
  - arrow=1.3.0
  - arrow-cpp=14.0.2
  - astor=0.8.1
  - astroid=3.2.2
  - astropy=6.1.0
  - astropy-iers-data=0.2024.5.27.0.30.8
  - asttokens=2.4.1
  - async-lru=2.0.4
  - atomicwrites=1.4.1
  - attrs=23.2.0
  - automat=22.10.0
  - autopep8=2.0.4
  - aws-c-auth=0.6.21
  - aws-c-cal=0.5.20
  - aws-c-common=0.8.5
  - aws-c-compression=0.2.16
  - aws-c-event-stream=0.2.17
  - aws-c-http=0.7.0
  - aws-c-io=0.13.12
  - aws-c-mqtt=0.7.13
  - aws-c-s3=0.2.1
  - aws-c-sdkutils=0.1.7
  - aws-checksums=0.1.14
  - aws-crt-cpp=0.18.16
  - aws-sdk-cpp=1.10.55
  - babel=2.14.0
  - backports=1.0
  - backports.functools_lru_cache=2.0.0
  - backports.tarfile=1.0.0
  - backports.tempfile=1.0
  - backports.weakref=1.0.post1
  - bcrypt=4.1.3
  - beautifulsoup4=4.12.3
  - binaryornot=0.4.4
  - binutils_impl_linux-64=2.40
  - binutils_linux-64=2.40
  - black=24.4.2
  - blas=1.0
  - bleach=6.1.0
  - blinker=1.8.2
  - blosc=1.21.5
  - bokeh=3.4.1
  - boltons=24.0.0
  - boost-cpp=1.85.0
  - botocore=1.34.106
  - bottleneck=1.3.8
  - brotli=1.0.9
  - brotli-bin=1.0.9
  - brotli-python=1.0.9
  - brunsli=0.1
  - bzip2=1.0.8
  - c-ares=1.28.1
  - c-blosc2=2.12.0
  - ca-certificates=2024.6.2
  - cached-property=1.5.2
  - cached_property=1.5.2
  - cachetools=5.3.3
  - catalogue=2.0.10
  - certifi=2024.2.2
  - cffi=1.16.0
  - cfitsio=4.2.0
  - chardet=5.2.0
  - charls=2.4.2
  - charset-normalizer=3.3.2
  - click=8.1.7
  - cloudpathlib=0.16.0
  - cloudpickle=3.0.0
  - clyent=1.2.2
  - colorama=0.4.6
  - colorcet=3.1.0
  - comm=0.2.2
  - commonmark=0.9.1
  - conda-content-trust=0.2.0
  - conda-pack=0.7.1
  - conda-package-handling=2.2.0
  - conda-package-streaming=0.9.0
  - conda-repo-cli=1.0.88
  - conda-suggest=0.1.1
  - conda-suggest-conda-forge=2021.8.24
  - conda-verify=3.4.2
  - confection=0.1.4
  - cons=0.4.6
  - constantly=15.1.0
  - contourpy=1.2.1
  - cookiecutter=2.6.0
  - cramjam=2.8.3
  - cryptography=42.0.7
  - cssselect=1.2.0
  - curl=8.7.1
  - cycler=0.12.1
  - cymem=2.0.8
  - cyrus-sasl=2.1.28
  - cython-blis=0.7.10
  - cytoolz=0.12.3
  - daal4py=2024.3.0
  - dal=2024.3.0
  - dask=2024.5.1
  - dask-core=2024.5.1
  - dask-expr=1.1.1
  - dataclasses=0.8
  - datasets=2.14.4
  - datashader=0.16.1
  - dav1d=1.2.1
  - dbus=1.13.18
  - debugpy=1.8.1
  - decorator=5.1.1
  - defusedxml=0.7.1
  - diff-match-patch=20230430
  - dill=0.3.7
  - distributed=2024.5.1
  - distro=1.9.0
  - docstring-to-markdown=0.15
  - docutils=0.21.2
  - entrypoints=0.4
  - et_xmlfile=1.1.0
  - etuples=0.3.9
  - exceptiongroup=1.2.0
  - executing=2.0.1
  - expat=2.6.2
  - filelock=3.14.0
  - flake8=7.0.0
  - flask=3.0.3
  - fmt=9.1.0
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.14.2
  - fonts-anaconda=1
  - fonts-conda-forge=1
  - fonttools=4.52.4
  - formulaic=1.0.1
  - fqdn=1.5.1
  - freetype=2.12.1
  - frozendict=2.4.4
  - frozenlist=1.4.1
  - fsspec=2024.5.0
  - future=1.0.0
  - gcc=12.3.0
  - gcc_impl_linux-64=12.3.0
  - gcc_linux-64=12.3.0
  - gensim=4.3.2
  - gflags=2.2.2
  - giflib=5.2.2
  - gitdb=4.0.11
  - gitpython=3.1.43
  - glib=2.80.2
  - glib-tools=2.80.2
  - glog=0.5.0
  - gmp=6.3.0
  - gmpy2=2.1.5
  - graphlib-backport=1.0.3
  - greenlet=3.0.3
  - grpc-cpp=1.48.2
  - gst-plugins-base=1.14.1
  - gstreamer=1.14.1
  - gxx=12.3.0
  - gxx_impl_linux-64=12.3.0
  - gxx_linux-64=12.3.0
  - h11=0.14.0
  - h2=4.1.0
  - h5py=3.11.0
  - hdf5=1.14.3
  - heapdict=1.0.1
  - holoviews=1.18.3
  - hpack=4.0.0
  - html5lib=1.1
  - httpcore=1.0.5
  - httpx=0.27.0
  - huggingface_hub=0.23.2
  - hvplot=0.10.0
  - hyperframe=6.0.1
  - hyperlink=21.0.0
  - icu=73.2
  - idna=3.7
  - imagecodecs=2023.1.23
  - imageio=2.34.1
  - imagesize=1.4.1
  - imbalanced-learn=0.12.3
  - importlib-metadata=7.1.0
  - importlib_metadata=7.1.0
  - importlib_resources=6.4.0
  - incremental=22.10.0
  - inflection=0.5.1
  - iniconfig=2.0.0
  - intake=2.0.5
  - intel-openmp=2023.1.0
  - interface_meta=1.3.0
  - intervaltree=3.1.0
  - ipykernel=6.29.3
  - ipython=8.24.0
  - ipython_genutils=0.2.0
  - ipywidgets=8.1.3
  - isoduration=20.11.0
  - isort=5.13.2
  - itemadapter=0.9.0
  - itemloaders=1.2.0
  - itsdangerous=2.2.0
  - jaraco.classes=3.4.0
  - jaraco.context=5.3.0
  - jaraco.functools=4.0.0
  - jedi=0.19.1
  - jeepney=0.8.0
  - jellyfish=1.0.4
  - jinja2=3.1.4
  - jmespath=1.0.1
  - joblib=1.4.2
  - jpeg=9e
  - jq=1.7.1
  - json5=0.9.25
  - jsonpatch=1.33
  - jsonpointer=2.4
  - jsonschema=4.22.0
  - jsonschema-specifications=2023.12.1
  - jsonschema-with-format-nongpl=4.22.0
  - jupyter=1.0.0
  - jupyter-lsp=2.2.5
  - jupyter_client=8.6.2
  - jupyter_console=6.6.3
  - jupyter_core=5.7.2
  - jupyter_events=0.10.0
  - jupyter_server=2.14.0
  - jupyter_server_terminals=0.5.3
  - jupyterlab=4.2.1
  - jupyterlab-variableinspector=3.2.1
  - jupyterlab_pygments=0.3.0
  - jupyterlab_server=2.27.2
  - jupyterlab_widgets=3.0.11
  - jupytext=1.16.2
  - jxrlib=1.1
  - kaleido-core=0.2.1
  - kernel-headers_linux-64=2.6.32
  - keyring=25.2.1
  - keyutils=1.6.1
  - kiwisolver=1.4.5
  - krb5=1.20.1
  - langcodes=3.4.0
  - language-data=1.2.0
  - lazy-object-proxy=1.10.0
  - lazy_loader=0.4
  - lcms2=2.15
  - ld_impl_linux-64=2.40
  - lerc=4.0.0
  - libabseil=20211102.0
  - libaec=1.1.3
  - libarchive=3.6.2
  - libavif=0.11.1
  - libblas=3.9.0
  - libboost=1.85.0
  - libboost-devel=1.85.0
  - libboost-headers=1.85.0
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libcblas=3.9.0
  - libclang=14.0.6
  - libclang13=14.0.6
  - libcups=2.3.3
  - libcurl=8.7.1
  - libdeflate=1.17
  - libedit=3.1.20230828
  - libev=4.33
  - libevent=2.1.12
  - libexpat=2.6.2
  - libffi=3.4.2
  - libgcc-devel_linux-64=12.3.0
  - libgcc-ng=13.2.0
  - libgfortran-ng=13.2.0
  - libgfortran5=13.2.0
  - libglib=2.80.2
  - libgomp=13.2.0
  - libhwloc=2.9.1
  - libiconv=1.17
  - liblapack=3.9.0
  - liblief=0.14.1
  - libllvm14=14.0.6
  - libmamba=1.5.8
  - libmambapy=1.5.8
  - libnghttp2=1.58.0
  - libnsl=2.0.1
  - libpng=1.6.43
  - libpq=12.17
  - libprotobuf=3.20.3
  - libsanitizer=12.3.0
  - libsodium=1.0.18
  - libsolv=0.7.29
  - libspatialindex=1.9.3
  - libsqlite=3.45.3
  - libssh2=1.11.0
  - libstdcxx-devel_linux-64=12.3.0
  - libstdcxx-ng=13.2.0
  - libthrift=0.15.0
  - libtiff=4.5.0
  - libuuid=2.38.1
  - libwebp-base=1.4.0
  - libxcb=1.16
  - libxcrypt=4.4.36
  - libxkbcommon=1.0.3
  - libxml2=2.10.4
  - libxslt=1.1.37
  - libzlib=1.2.13
  - libzopfli=1.0.3
  - linearmodels=6.0
  - linkify-it-py=2.0.3
  - llvm-openmp=18.1.6
  - llvmlite=0.42.0
  - locket=1.0.0
  - logical-unification=0.4.6
  - lxml=5.2.1
  - lz4=4.3.3
  - lz4-c=1.9.4
  - lzo=2.10
  - marisa-trie=1.1.0
  - markdown=3.6
  - markdown-it-py=3.0.0
  - markupsafe=2.1.5
  - mathjax=2.7.7
  - matplotlib=3.8.4
  - matplotlib-base=3.8.4
  - matplotlib-inline=0.1.7
  - mccabe=0.7.0
  - mdit-py-plugins=0.4.1
  - mdurl=0.1.2
  - menuinst=2.1.0
  - minikanren=1.0.3
  - mistune=3.0.2
  - mkl=2023.2.0
  - mkl-service=2.4.1
  - mkl_fft=1.3.9
  - mkl_random=1.2.6
  - more-itertools=10.2.0
  - mpc=1.3.1
  - mpfr=4.2.1
  - mpi=1.0
  - mpich=4.2.1
  - mpmath=1.3.0
  - msgpack-python=1.0.8
  - multidict=6.0.5
  - multipledispatch=0.6.0
  - multiprocess=0.70.15
  - multitasking=0.0.9
  - munkres=1.1.4
  - murmurhash=1.0.10
  - mypy=1.10.0
  - mypy_extensions=1.0.0
  - mysql=5.7.24
  - nbclient=0.10.0
  - nbconvert=7.16.4
  - nbconvert-core=7.16.4
  - nbconvert-pandoc=7.16.4
  - nbformat=5.10.4
  - ncurses=6.5
  - nest-asyncio=1.6.0
  - networkx=3.3
  - nlopt=2.7.1
  - nltk=3.8.1
  - notebook=7.2.0
  - notebook-shim=0.2.4
  - nspr=4.35
  - nss=3.100
  - numba=0.59.1
  - numexpr=2.8.7
  - numpy=1.26.4
  - numpy-base=1.26.4
  - numpydoc=1.7.0
  - oniguruma=6.9.9
  - openjpeg=2.5.0
  - openpyxl=3.1.2
  - openssl=3.3.1
  - orc=1.7.4
  - overrides=7.7.0
  - packaging=24.0
  - pandas=2.2.2
  - pandoc=3.2
  - pandocfilters=1.5.0
  - panel=1.4.3
  - param=2.1.0
  - parsel=1.9.1
  - parso=0.8.4
  - partd=1.4.2
  - patch=2.7.6
  - patchelf=0.17.2
  - pathlib=1.0.1
  - pathspec=0.12.1
  - pathy=0.10.2
  - patsy=0.5.6
  - pcre=8.45
  - pcre2=10.43
  - peewee=3.17.3
  - pep8=1.7.1
  - pexpect=4.9.0
  - pickleshare=0.7.5
  - pillow=10.3.0
  - pip=24.0
  - pkce=1.0.3
  - pkginfo=1.10.0
  - pkgutil-resolve-name=1.3.10
  - platformdirs=4.2.2
  - plotly=5.22.0
  - pluggy=1.5.0
  - ply=3.11
  - preshed=3.0.9
  - prometheus_client=0.20.0
  - prompt-toolkit=3.0.42
  - prompt_toolkit=3.0.42
  - protego=0.3.1
  - protobuf=3.20.3
  - psutil=5.9.8
  - pthread-stubs=0.4
  - ptyprocess=0.7.0
  - pure_eval=0.2.2
  - py-cpuinfo=9.0.0
  - py-lief=0.14.1
  - pyarrow=14.0.2
  - pyarrow-hotfix=0.6
  - pyasn1=0.6.0
  - pyasn1-modules=0.4.0
  - pybind11-abi=4
  - pycodestyle=2.11.1
  - pycosat=0.6.6
  - pycparser=2.22
  - pyct=0.5.0
  - pycurl=7.45.3
  - pydantic=2.7.2
  - pydantic-core=2.18.3
  - pydeck=0.8.0
  - pydispatcher=2.0.5
  - pydocstyle=6.3.0
  - pyerfa=2.0.1.4
  - pyflakes=3.2.0
  - pygments=2.18.0
  - pyhdfe=0.2.0
  - pyjwt=2.8.0
  - pylint=3.2.2
  - pylint-venv=3.0.3
  - pyls-spyder=0.4.0
  - pyodbc=5.1.0
  - pyopenssl=24.0.0
  - pyparsing=3.1.2
  - pyperclip=1.8.2
  - pyqt=5.15.10
  - pyqt5-sip=12.13.0
  - pyqtwebengine=5.15.10
  - pysocks=1.7.1
  - pytables=3.9.2
  - pytensor=2.22.1
  - pytensor-base=2.22.1
  - pytest=8.2.1
  - python=3.11.9
  - python-dateutil=2.9.0
  - python-dotenv=1.0.1
  - python-fastjsonschema=2.19.1
  - python-json-logger=2.0.7
  - python-kaleido=0.2.1
  - python-libarchive-c=5.1
  - python-lmdb=1.4.1
  - python-lsp-black=2.0.0
  - python-lsp-jsonrpc=1.1.2
  - python-lsp-server=1.11.0
  - python-lsp-server-base=1.11.0
  - python-slugify=8.0.4
  - python-snappy=0.7.1
  - python-tzdata=2024.1
  - python-xxhash=3.4.1
  - python_abi=3.11
  - pytoolconfig=1.2.5
  - pytz=2024.1
  - pyviz_comms=3.0.2
  - pywavelets=1.4.1
  - pyxdg=0.28
  - pyyaml=6.0.1
  - pyzmq=26.0.3
  - qdarkstyle=3.2.3
  - qstylizer=0.2.3
  - qt-main=5.15.2
  - qt-webengine=5.15.9
  - qtawesome=1.3.1
  - qtconsole=5.5.2
  - qtconsole-base=5.5.2
  - qtpy=2.4.1
  - queuelib=1.7.0
  - re2=2022.04.01
  - readline=8.2
  - referencing=0.35.1
  - regex=2024.5.15
  - reproc=14.2.4.post0
  - reproc-cpp=14.2.4.post0
  - requests=2.32.3
  - requests-file=2.1.0
  - requests-toolbelt=1.0.0
  - responses=0.25.0
  - rfc3339-validator=0.1.4
  - rfc3986-validator=0.1.1
  - rich=10.16.2
  - ripgrep=14.1.0
  - rope=1.13.0
  - rpds-py=0.18.1
  - rtree=1.2.0
  - ruamel.yaml=0.18.6
  - ruamel.yaml.clib=0.2.8
  - ruamel_yaml=0.15.80
  - s2n=1.3.31
  - s3fs=2024.5.0
  - safetensors=0.4.3
  - scikit-image=0.22.0
  - scikit-learn=1.5.0
  - scikit-learn-intelex=2024.3.0
  - scipy=1.13.0
  - scrapy=2.11.2
  - seaborn=0.13.2
  - seaborn-base=0.13.2
  - secretstorage=3.3.3
  - semver=3.0.2
  - send2trash=1.8.3
  - service-identity=21.1.0
  - service_identity=21.1.0
  - setproctitle=1.3.3
  - setuptools=70.0.0
  - shellingham=1.5.4
  - sip=6.7.12
  - six=1.16.0
  - skglm=0.3.1
  - smart_open=5.2.1
  - smmap=5.0.0
  - snappy=1.1.10
  - sniffio=1.3.1
  - snowballstemmer=2.2.0
  - sortedcontainers=2.4.0
  - soupsieve=2.5
  - spacy=3.7.3
  - spacy-legacy=3.0.12
  - spacy-loggers=1.0.5
  - sphinx=7.3.7
  - sphinxcontrib-applehelp=1.0.8
  - sphinxcontrib-devhelp=1.0.6
  - sphinxcontrib-htmlhelp=2.0.5
  - sphinxcontrib-jsmath=1.0.1
  - sphinxcontrib-qthelp=1.0.7
  - sphinxcontrib-serializinghtml=1.1.10
  - spyder=5.5.4
  - spyder-kernels=2.5.1
  - sqlalchemy=2.0.30
  - sqlite=3.45.3
  - srsly=2.4.8
  - stack_data=0.6.2
  - statsmodels=0.14.2
  - streamlit=1.35.0
  - sympy=1.12
  - sysroot_linux-64=2.12
  - tabulate=0.9.0
  - tbb=2021.9.0
  - tbb4py=2021.9.0
  - tblib=3.0.0
  - tenacity=8.3.0
  - terminado=0.18.1
  - text-unidecode=1.3
  - textdistance=4.6.2
  - thinc=8.2.3
  - threadpoolctl=3.5.0
  - three-merge=0.1.1
  - tifffile=2023.8.12
  - tinycss2=1.3.0
  - tk=8.6.13
  - tldextract=5.1.2
  - tokenizers=0.19.1
  - toml=0.10.2
  - tomli=2.0.1
  - tomlkit=0.12.5
  - toolz=0.12.1
  - tornado=6.4
  - tqdm=4.66.4
  - traitlets=5.14.3
  - transformers=4.41.1
  - truststore=0.8.0
  - twisted=24.3.0
  - typer=0.9.4
  - types-python-dateutil=2.9.0.20240316
  - types-pyyaml=6.0.12.20240311
  - typing-extensions=4.11.0
  - typing_extensions=4.11.0
  - typing_utils=0.1.0
  - tzdata=2024a
  - tzlocal=5.2
  - uc-micro-py=1.0.3
  - ujson=5.10.0
  - unidecode=1.3.8
  - unixodbc=2.3.12
  - uri-template=1.3.0
  - urllib3=2.2.1
  - utf8proc=2.6.1
  - validators=0.28.3
  - w3lib=2.1.2
  - wasabi=1.1.2
  - watchdog=4.0.1
  - wcwidth=0.2.13
  - weasel=0.3.4
  - webcolors=1.13
  - webencodings=0.5.1
  - websocket-client=1.8.0
  - werkzeug=3.0.3
  - whatthepatch=1.0.5
  - wheel=0.43.0
  - widgetsnbextension=4.0.11
  - wrapt=1.16.0
  - wurlitzer=3.1.0
  - xarray=2024.5.0
  - xorg-libxau=1.0.11
  - xorg-libxdmcp=1.1.3
  - xxhash=0.8.2
  - xyzservices=2024.4.0
  - xz=5.4.6
  - yaml=0.2.5
  - yaml-cpp=0.8.0
  - yapf=0.40.1
  - yarl=1.9.4
  - yfinance=0.2.40
  - zeromq=4.3.5
  - zfp=1.0.1
  - zict=3.0.0
  - zipp=3.17.0
  - zlib=1.2.13
  - zlib-ng=2.0.7
  - zope=1.0
  - zope.interface=6.4.post2
  - zstandard=0.19.0
  - zstd=1.5.6